### ISSUE TITLE
Failed to activate the filesize package

### ISSUE THREAD

**Issue by montogeek** [mkxml/atom-filesize#15]
I got this error after updating to 1.11.0

**Atom Version**: 1.11.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [filesize](https://github.com/mkautzmann/atom-filesize) package, v0.4.2
### Stack Trace

Failed to activate the filesize package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.module.exports.activate (/Users/montogeek/.atom/packages/filesize/lib/filesize.coffee:46:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```
### Commands

```
     -0:01.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tabs-to-spaces",
      "editorconfig",
      "git-time-machine",
      "language-thrift",
      "tree-view",
      "enzyme-snippets",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "genesis-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-chai-snippets, v0.3.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-panda-syntax, v0.13.0 (inactive)
docblockr, v0.8.7 (inactive)
duotone-dark-red-syntax, v0.3.2 (inactive)
editorconfig, v1.4.1 (inactive)
emmet, v2.4.3 (inactive)
enzyme-snippets, v0.1.0 (inactive)
file-icons, v1.7.20 (inactive)
filesize, v0.4.2 (inactive)
genesis-ui, v0.5.0 (inactive)
git-plus, v5.18.0 (inactive)
haskell-grammar, v0.4.0 (inactive)
highlight-selected, v0.11.2 (inactive)
language-babel, v2.44.1 (inactive)
language-ini, v1.16.0 (inactive)
language-ocaml, v1.1.2 (inactive)
language-swift, v0.4.0 (inactive)
language-thrift, v1.0.2 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
material-ui, v1.0.9 (inactive)
merge-conflicts, v1.4.4 (inactive)
nova-atom-syntax, v1.3.1 (inactive)
nova-atom-ui, v1.2.3 (inactive)
nuclide, v0.175.0 (inactive)
nuclide-format-js, v0.0.36 (inactive)
oceanic-next, v0.4.0 (inactive)
pigments, v0.37.0 (inactive)
pretty-json, v1.6.1 (inactive)
project-manager, v3.2.3 (inactive)
react-es6-snippets, v0.3.0 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
synced-sidebar, v0.4.3 (inactive)
tool-bar, v1.0.1 (inactive)
vim-mode-plus, v0.60.0 (inactive)
wakatime, v6.0.10 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by mkxml** [comment]
Hello @montogeek, thanks for reporting this situation.

I'm working on a complete rewrite of the package that may go out today or tomorrow. It should solve this issue as well. I will close this issue when confirmed.

**Comment by montogeek** [comment]
Thanks! And cool for the code upgrade!

**Comment by mkxml** [comment]
Hey @montogeek, the 1.0.0 version was just released. Please update the package and see if everything works. I'll close this issue when you confirm everything is fine to you.

Thanks!

**Comment by montogeek** [comment]
After the update Atom failed to activate it.
Restart Atom solved it :)

Thanks!

**Comment by mkxml** [comment]
OK, feel free to report any future problems.

**Comment by gihrig** [comment]
I received an error on updating to fileSize 1.0.0 (was directed here by link in error dialog)

Steps to reproduce:
1. Receive filesize update notification
2. Update fileSize from Atom Settings > Available updates.

Perform a Window Reload and all is well :-)

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [filesize](https://github.com/mkautzmann/atom-filesize) package, v1.0.0

### Stack Trace

Failed to activate the filesize package

```
At this.constructor.buildHtml is not a function

TypeError: this.constructor.buildHtml is not a function
    at View (/Applications/Development/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:155:33)
    at FilesizeView (/Users/glen/.atom/packages/filesize/lib/filesize-view.coffee:12:49)
    at Object.activate (/Users/glen/.atom/packages/filesize/lib/filesize.js:37:17)
    at Package.module.exports.Package.activateNow (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Development/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Development/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Development/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Development/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:397:31
```

### Commands

```
  4x -6:56.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:54.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -6:54.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:54.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -6:54.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:54.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -6:52.8.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -6:48.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:45.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:19.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:36.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:34.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:31.3.0 core:undo (atom-text-editor.editor.is-focused)
     -5:13.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:11 core:save (atom-text-editor.editor.is-focused)
     -3:29.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "todo-list",
      "standard-formatter",
      "linter-js-standard",
      "linter-sass-lint",
      "jsformat",
      "linter-scss-lint",
      "standardjs-snippets",
      "css-to-inline",
      "terminal-plus",
      "csslint",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "linter-csslint",
      "language-sass"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "color-picker",
      "csslint"
    ],
    "projectHome": "/Users/glen/Documents/JavaScript",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-bootstrap4, v1.4.0 (active)
atom-chai-snippets, v0.3.0 (active)
atom-easy-jsdoc, v4.7.1 (active)
atom-react-native-autocomplete, v0.0.27 (active)
atom-react-preview, v2.0.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-json, v5.1.0 (active)
autocomplete-modules, v1.6.7 (active)
chary-tree-view, v0.2.3 (active)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.21 (active)
filesize, v1.0.0 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
keybinding-cheatsheet, v0.1.1 (inactive)
language-javascript-jsx, v0.3.7 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (inactive)
linter-eslint, v7.3.2 (active)
linter-stylelint, v3.3.1 (active)
native-color-picker, v0.2.0 (inactive)
open-in-browsers, v0.0.19 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
react, v0.16.0 (active)
react-es6-snippets, v0.3.0 (active)
react-snippets, v0.5.0 (active)
redux-snippets, v0.2.2 (active)
sync-settings, v0.7.2 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mkxml** [comment]
Thanks for reporting @gihrig. From your stack trace I can see that it appears to be an error thrown when deactivating the old version. The space-pen dependency is not even there anymore...

Atom should handle this better, I don't think there is something I can do now if not to recommend users to restart Atom after the update.

It should not throw exceptions from now on though, the deactivation process should happen gracefully. You can test this by disabling and re-enabling the package to see if any error is thrown.

**Comment by gihrig** [comment]
> It should not throw exceptions from now on though, the deactivation process should happen gracefully. You can test this by disabling and re-enabling the package to see if any error is thrown.

That's right, I have confirmed no error on deactivate/activate.
