### ISSUE TITLE
Uncaught TypeError: statusBar.appendLeft is not a function

### ISSUE THREAD

**Issue by capaj** [mkxml/atom-filesize#9]
Upon startup

**Atom Version**: 1.2.0-beta0
**System**: Debian GNU/Linux
**Thrown From**: [filesize](https://github.com/mkautzmann/atom-filesize) package, v0.2.0
### Stack Trace

Uncaught TypeError: statusBar.appendLeft is not a function

```
At /home/capaj/.atom/packages/filesize/lib/filesize-view.coffee:28

TypeError: statusBar.appendLeft is not a function
    at FilesizeView.module.exports.FilesizeView.show (/home/capaj/.atom/packages/filesize/lib/filesize-view.coffee:28:18)
    at FilesizeView.module.exports.FilesizeView.display (/home/capaj/.atom/packages/filesize/lib/filesize-view.coffee:20:8)
    at FilesizeCalculator.<anonymous> (/home/capaj/.atom/packages/filesize/lib/filesize.coffee:65:23)
    at FilesizeCalculator.module.exports.FilesizeCalculator.makeReadable (/home/capaj/.atom/packages/filesize/lib/filesize-calculator.coffee:93:16)
    at /home/capaj/.atom/packages/filesize/lib/filesize-calculator.coffee:38:8
    at /home/capaj/.atom/packages/filesize/lib/filesize-calculator.coffee:66:20
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
coffee-links, v0.1.0
coffee-refactor, v0.7.0
editorconfig, v1.2.0
file-type-icons, v0.7.3
filesize, v0.2.0
hyperclick, v0.0.32
js-hyperclick, v1.3.0
js-refactor, v0.6.0
jspm-dev-buddy, v0.0.1
language-cjsx, v0.3.0
language-diff, v0.3.1
language-dotenv, v1.0.0
language-gitignore, v0.2.0
language-nginx, v0.6.1
language-soy, v0.3.0
linter, v1.10.0
linter-js-standard, v3.2.1
local-history, v3.2.3
open-recent, v2.3.0
react, v0.12.10
refactor, v0.6.0
standard-formatter, v1.2.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by mkxml** [comment]
Do you have the `status-bar` built-in package activated? It's dependent on that one, I just discovered that atom 1.0 has a way to specify these kind of dependencies and I will include to the project soon.

We're also in the middle of the release of 0.3.0 with some new features so keep an eye out for updates!

**Comment by mkxml** [comment]
Fixed in commit 18e62abd742f81b85e9ce89e0f28e6705ba82c40

@capaj OK, the `status-bar` component was now added as a formal dependency. Please check update to version `0.3.1` as test it out. I appreciate your feedback.

Will reopen this issue if you find any new problem.

Thank you.

**Comment by danielsharvey** [comment]
I still have this error.

```
atom 1.2.0-beta1
filesize 0.3.1
status-bar 0.80.0
```

**Comment by mkxml** [comment]
Strange, I will do some extra checks to see if I can reproduce.

**Comment by zenopopovici** [comment]
I also have this error.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [filesize](https://github.com/mkautzmann/atom-filesize) package, v0.3.1

### Stack Trace

Uncaught TypeError: statusBar.appendLeft is not a function

```
At /Users/Zeno/.atom/packages/filesize/lib/filesize-view.coffee:120

TypeError: statusBar.appendLeft is not a function
  at FilesizeView.module.exports.FilesizeView.show (/Users/Zeno/.atom/packages/filesize/lib/filesize-view.coffee:120:18)
  at FilesizeView.module.exports.FilesizeView.display (/Users/Zeno/.atom/packages/filesize/lib/filesize-view.coffee:26:8)
  at FilesizeCalculator.<anonymous> (/Users/Zeno/.atom/packages/filesize/lib/filesize.coffee:93:23)
  at FilesizeCalculator.module.exports.FilesizeCalculator.makeReadable (/Users/Zeno/.atom/packages/filesize/lib/filesize-calculator.coffee:141:16)
  at FilesizeCalculator.<anonymous> (/Users/Zeno/.atom/packages/filesize/lib/filesize-calculator.coffee:55:8)
  at /Users/Zeno/.atom/packages/filesize/lib/filesize-calculator.coffee:111:20
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -6:14 terminal-panel:new (atom-text-editor.editor.mini.is-focused)
     -5:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:41.3.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  4x -3:41.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

``` json
{
  "core": {
    "projectHome": "/Users/Zeno/Sites",
    "disabledPackages": [
      "language-csharp",
      "language-clojure",
      "language-c",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-xml",
      "language-yaml",
      "language-toml",
      "alignment",
      "todo-list",
      "todo-list",
      "symbols-tree-view",
      "package-generator",
      "SFTP-deployment",
      "atom-ftp-editor",
      "welcome",
      "timecop",
      "styleguide",
      "dev-live-reload",
      "atom-pair",
      "minimap-codeglance",
      "auto-update-packages",
      "emmet",
      "linter-stylint"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".gitignore",
      "bower.js",
      "bower.css",
      "bower_components",
      "node_modules",
      "css",
      "plugins",
      "uploads",
      "main*.js",
      "main*.map",
      "main*.css"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": []
  },
  "filesize": {}
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
Stylus, v1.2.1
atom-alignment, v0.12.1
atom-shortcuts, v0.0.2
autocomplete-paths, v1.0.2
copy-filename, v1.0.1
docblockr, v0.7.3
editorconfig, v1.2.2
file-type-icons, v0.7.3
filesize, v0.3.1
linter, v1.10.0
linter-alex, v1.5.1
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-less, v2.2.0
linter-stylint-h, v0.0.12
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-selection, v4.3.1
pigments, v0.18.1
pretty-json, v0.4.1
regex-railroad-diagram, v0.10.4
resize-indent, v0.2.1
svg-preview, v0.6.1
synced-sidebar, v0.4.2
tab-close-double-click, v1.0.1
tag, v0.3.0
terminal-plus, v0.14.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by mkxml** [comment]
OK, changed the way `filesize` relate to the `status-bar` to the new approach introduced in Atom 1.1.0. So please make sure your Atom is updated and update `filesize` to `0.4.1`.

Please confirm if it is fine now so I can close the issue.

Thank you.

**Comment by zenopopovici** [comment]
Yep. It's fixed! Thanks a lot mate!

**Comment by mkxml** [comment]
OK @zenopopovici. Closing the issue for now, if anyone gets the same error again please let me know. Thank you all for reporting this! :smile:

**Comment by danielsharvey** [comment]
+1 fixed. Thanks!
